[project]
name = "agno-ai-agent-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.5.4",
    "duckduckgo-search>=8.0.2",
    "ipykernel>=6.29.5",
    "openai>=1.82.0",
]
