[project]
name = "google-gemini-api-usages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.24.0",
    "ipykernel>=6.29.5",
]
