[project]
name = "crawl4ai-implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crawl4ai>=0.6.3",
    "ipykernel>=6.30.1",
    "playwright>=1.52.0",
]
