"""Prompt templates for the application"""

from .templates import (
    SQL_GENERATION_SYSTEM_PROMPT,
    SQL_GENERATION_SYSTEM_PROMPT_SINGLE_TABLE,
    RESPONSE_GENERATION_SYSTEM_PROMPT
)

__all__ = [
    "SQL_GENERATION_SYSTEM_PROMPT",
    "SQL_GENERATION_SYSTEM_PROMPT_SINGLE_TABLE",
    "RESPONSE_GENERATION_SYSTEM_PROMPT"
]
