[project]
name = "testing-gradio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.32.0",
    "openai-gradio>=0.0.6",
]
